import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../globals.css'
import { notFound } from 'next/navigation'
import { routing } from '@/i18n/routing'
import React from 'react'
import { hasLocale, NextIntlClientProvider } from 'next-intl'
import { UserNavbar } from '@/components/shared/navbar/user-navbar'
import { auth } from '@/features/auth/config/auth'
import { SessionProvider } from 'next-auth/react'
import { NuqsAdapter } from 'nuqs/adapters/next'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ locale: string }>
}) {
  const { locale } = await params
  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  const session = await auth()

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NuqsAdapter>
          <SessionProvider session={session}>
            <NextIntlClientProvider>
              <div>
                <UserNavbar />
                {children}
              </div>
            </NextIntlClientProvider>
          </SessionProvider>
        </NuqsAdapter>
      </body>
    </html>
  )
}
